<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Tambah Data</name>
   <tag></tag>
   <elementGuidId>fd680878-81f6-40c6-843c-3d22b62ca2df</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='btnAddSectionSkill']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btnAddSectionSkill</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#btnAddSectionSkill</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8e6fc374-f6fc-483a-baab-8d4bc23fa33d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnAddSectionSkill</value>
      <webElementGuid>e26ba5f0-6489-45a5-9ea8-265ea6906f46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-outline-primary p-2</value>
      <webElementGuid>423ce929-bb36-4e98-b6d9-e865384aaf21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>autoSave()</value>
      <webElementGuid>c2a8b105-1709-4186-88a5-54da6a30c539</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                             Tambah Data
                                        </value>
      <webElementGuid>28fc29fe-eef8-4ba4-bc10-8c165b7e7334</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnAddSectionSkill&quot;)</value>
      <webElementGuid>ef4f9bfc-e7eb-45ca-ab79-82bc408a2f03</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='btnAddSectionSkill']</value>
      <webElementGuid>23c15ac6-c086-448b-aa32-07cc058e6fd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form']/div[4]/div[2]/div/a</value>
      <webElementGuid>83860d71-96cf-42f3-84ee-ddaf80509adb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kategori'])[1]/following::a[2]</value>
      <webElementGuid>d797e385-ce5a-48db-8d60-59af77661a67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tingkat'])[4]/following::a[2]</value>
      <webElementGuid>c8c62f73-c562-4d66-8d9f-f71c72be50a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Riwayat Pekerjaan'])[1]/preceding::a[1]</value>
      <webElementGuid>4af62988-f8b5-49f7-9db8-f75bc8831d67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'autoSave()')])[3]</value>
      <webElementGuid>086ce408-7992-410e-a38a-666c9bb7351d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/a</value>
      <webElementGuid>d6fd7ee8-d771-4d41-ab22-f6d9b045adac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'btnAddSectionSkill' and @href = 'autoSave()' and (text() = '
                                             Tambah Data
                                        ' or . = '
                                             Tambah Data
                                        ')]</value>
      <webElementGuid>4d69736b-26bd-454f-8499-a6a78c7a6ae1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
