<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Detail</name>
   <tag></tag>
   <elementGuidId>a7c6207a-7f1f-47bd-8432-2d99f796e79c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//a[@id='btnDetail'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div:nth-child(15) > .row > #btnDetail</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e5ff176c-77ac-4b5a-b4e8-b5c682631c73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/job/28</value>
      <webElementGuid>06df11bf-d7cd-4b6a-b923-e0865651e944</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-success col-md-3</value>
      <webElementGuid>bd06299c-6009-486f-950e-6b3aff65cc5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnDetail</value>
      <webElementGuid>db085a9a-bba6-4489-8ab3-7305e6ea66cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Detail</value>
      <webElementGuid>d73178d0-d607-40e1-b36e-f97dac637ce8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jobDetail&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-6 mb-2&quot;]/div[@class=&quot;card rounded-3&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;mt-auto&quot;]/div[@class=&quot;row mt-3 mx-auto&quot;]/a[@id=&quot;btnDetail&quot;]</value>
      <webElementGuid>c6d28bea-8e53-4808-b9ab-44204a14f8d1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//a[@id='btnDetail'])[2]</value>
      <webElementGuid>5f08dccb-3466-4db7-a610-bdb7aa233221</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='jobDetail']/div/div[2]/div/div/div[2]/div/a</value>
      <webElementGuid>0a0ec9b3-e093-4a6f-aff7-1b2b8fbe033a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Detail')])[2]</value>
      <webElementGuid>3edf6942-b6fb-456a-a9a5-d890e1d347ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Requirements:'])[1]/following::a[1]</value>
      <webElementGuid>ac2bd709-56d5-495d-a997-b1f09cc66301</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Detail'])[1]/following::a[1]</value>
      <webElementGuid>123d4eb3-4d5a-4ff3-b20a-c57b2a635cc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Requirement :'])[1]/preceding::a[1]</value>
      <webElementGuid>aa5ca271-276c-484c-aecc-3b9a173a6415</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/job/28')]</value>
      <webElementGuid>9134bfa4-db03-4e77-9186-1218a4bddc5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/a</value>
      <webElementGuid>645ba3a4-9c2b-4761-ab72-2d48e9cac897</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/job/28' and @id = 'btnDetail' and (text() = 'Detail' or . = 'Detail')]</value>
      <webElementGuid>581b9eec-f1ee-41f8-a781-73ddf1c71d28</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
