<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Selesai</name>
   <tag></tag>
   <elementGuidId>762a1693-6206-44c3-ba49-577bf29aff79</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='body']/div[13]/div/div[6]/a[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.introjs-button.introjs-nextbutton.introjs-donebutton</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Selesai&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>aad2059b-d627-459c-9a3d-dd69b0ebdcdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a0d0f84e-cc01-4be8-94df-076f9109aef7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>7b77bfd0-df60-42fe-b619-65836a9769e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>introjs-button introjs-nextbutton introjs-donebutton</value>
      <webElementGuid>8838aa68-c1fa-41a2-b319-6c9f710b450d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Selesai</value>
      <webElementGuid>ee078e09-4b25-4d7f-b10d-549e13c25edb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;body&quot;)/div[@class=&quot;introjs-tooltipReferenceLayer introjs-fixedTooltip&quot;]/div[@class=&quot;introjs-tooltip introjs-bottom-left-aligned&quot;]/div[@class=&quot;introjs-tooltipbuttons&quot;]/a[@class=&quot;introjs-button introjs-nextbutton introjs-donebutton&quot;]</value>
      <webElementGuid>ba3813db-cfdc-4135-ab17-21a90f782bd6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='body']/div[13]/div/div[6]/a[2]</value>
      <webElementGuid>7338c23c-5432-4b39-8a93-35ca030321e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Selesai')]</value>
      <webElementGuid>54fe41d0-29e9-48bc-b199-b79b42844b3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kembali'])[1]/following::a[1]</value>
      <webElementGuid>eeb810d1-4e8a-46fa-aab9-faed90abebc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selain itu, Anda juga bisa membagikan CV Anda baik ke sosial media, maupun berupa link'])[1]/following::a[9]</value>
      <webElementGuid>51d028dc-b48a-49bd-a8f7-b85ea792c976</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Selesai']/parent::*</value>
      <webElementGuid>a773f758-c6fa-4fe0-9f42-49194495a0e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/a[2]</value>
      <webElementGuid>aeb29c7d-24b3-4bdd-a706-9eab97c5b7c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Selesai' or . = 'Selesai')]</value>
      <webElementGuid>6d015bbf-9d93-461e-a2ad-05664c75d8bb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
