<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tanggal Lahir_inputBirthDate</name>
   <tag></tag>
   <elementGuidId>14619316-9d35-4f0c-a359-0056076be3b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputBirthDate']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#inputBirthDate</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#inputBirthDate</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d1685dfc-288f-4333-822a-a3b4e6a972d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>cc1a07d0-c46f-42b8-a71a-80920f312985</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputBirthDate</value>
      <webElementGuid>83dc9f6d-22e4-4391-b6a7-75b20873ee0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>4bed0c82-4329-4e65-ab07-bb1a1a2486a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control required</value>
      <webElementGuid>f74f8d32-0561-4bb1-98de-b08f2b2b2e1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>
                                                   if($(this).val() === ''){
                                                   $('#frame').contents().find('#txtDateOfBirth').text('______').fadeTo(100, 0.3, function() { $(this).fadeTo(100, 1.0); })
                                                   $('#txtDateOfBirth').text('______').fadeTo(100, 0.3, function() { $(this).fadeTo(100, 1.0); })
                                                   } else {
                                                   $('#frame').contents().find('#txtDateOfBirth').text(dateFormatBirthDate($(this).val())).fadeTo(100, 0.3, function() { $(this).fadeTo(100, 1.0); })
                                                   $('#txtDateOfBirth').text(dateFormatBirthDate($(this).val())).fadeTo(100, 0.3, function() { $(this).fadeTo(100, 1.0); })
                                                   } autoSave();</value>
      <webElementGuid>b762d791-73e7-4f2f-9228-88f9a92cb761</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputBirthDate&quot;)</value>
      <webElementGuid>39284473-dfc2-4793-9fa9-b2b7f08e6b90</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputBirthDate']</value>
      <webElementGuid>c3a3e721-5cd3-45e3-a12f-049f8792eb17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='personalSection']/div[2]/div/input</value>
      <webElementGuid>ffc3be52-f58f-4493-8407-23b0d04b8297</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>c6a28a29-6a77-4ddf-acda-6b73964e39aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'inputBirthDate' and @type = 'date']</value>
      <webElementGuid>f11667fe-1675-443e-abdb-482ec34c4eca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
