<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Alamat_inputAddress</name>
   <tag></tag>
   <elementGuidId>819ea524-650f-47df-b29b-d578de27e4b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='inputAddress']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#inputAddress</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Alamat Lengkap&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>03bf487e-3089-4bac-995f-e85385b20fc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>autocomplete_off_cv_address</value>
      <webElementGuid>730fe97b-42f3-4db3-b719-97d11f5d7d33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputAddress</value>
      <webElementGuid>1cdc1e2c-6217-4df5-9ee7-571d7127b862</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3c035c3c-a78c-4538-9233-16588f7d44b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control required</value>
      <webElementGuid>f1b2ede1-e9d8-44fa-9d65-6fe61e5d76a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7578ff2f-8b39-417d-a5ec-601d71c2f8a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Alamat Lengkap</value>
      <webElementGuid>336cb286-025d-4365-ae3b-1a114d3fec9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>setAddress(); autoSave(); validateRequire($(this));</value>
      <webElementGuid>9641f264-ccf7-48d7-8953-8ec19cd8cf3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputAddress&quot;)</value>
      <webElementGuid>969e124f-b062-4a8f-83cf-1501ff44403c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='inputAddress']</value>
      <webElementGuid>727f50fa-a553-4d09-87eb-4359852c6f10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='personalSection']/div[6]/div/div[2]/div/textarea</value>
      <webElementGuid>8a4718ae-6ba3-4f30-b979-6402f43cce0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>cfb6150a-1eac-4a9d-8c6c-d8f4fc402e6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'inputAddress' and @type = 'text' and @placeholder = 'Alamat Lengkap']</value>
      <webElementGuid>abbca865-5434-401a-91d0-504a4bac2bad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
